sudo: required
env:
  matrix:
    - PLATFORM=centos DISTRO=el OS_VERSION=7 DOCKER_IMAGE=centos:centos7
    - PLATFORM=debian DISTRO=debian OS_VERSION=jessie DOCKER_IMAGE=debian:jessie
    - PLATFORM=ubuntu DISTRO=ubuntu OS_VERSION=trusty DOCKER_IMAGE=ubuntu:trusty
    - PLATFORM=ubuntu DISTRO=ubuntu OS_VERSION=xenial DOCKER_IMAGE=ubuntu:xenial
  global:
    - secure: "lRGEuvKHvW5hjSnOYR/jxdaxs3iGyTt9z+e94rwh2hfKXOsc07nxlCmKIlwioJb6ka/tKIcaxZYNHTT1M+K6ONyt+J1bD0MWJqA03AYH8mppXFtdBxVC7YDqwWGGV0p/kdJ0qWFeEhPJi3i92ZJtvpGWyi0B/ECzgwi4ftGNysMz/FjFNIGSgm4mFhUjDAA3dTEaOizb63LuJny6GRYHojJUYelbg3u86q7ta/fBbWgtctlo6P+yzTh+ksU5G3pwt5pWSpVdz4eU/4QQmQZZAvI90d/i8JSFz/wtrLAsk1P1eSjiqubI3qXWyiXhDfIWF4+Oy3Q1Femom3VN1P61mTC+2viiitH2uKp1VjR0Ucp3TOc9fmda1IojHq9WX6VOV1Od9fJkZ8MSVtiCMhiWQdjqs4xyHTzOutl7e/DcKXEWDVRHvd1QGi7/ZbYzATkAOsLpIzRNmrmcuCmK4giVge6POXWNsduIu8mCKLZWGz3djKv4CIwQXpgWcnYPVKK25eAKIJF0dBDfoNIC2jXSyN3zpILf3L3LTjYRFwhhg7ldHZ2LGQrGcGD/kswSZZEFE1YPzcBX8nH+xXTCaTXOmWDMmS5j1bla4acF9edQsofFpQRF21LeLQ75/UdH4E8yfj3A9vswjA/EGlGcEW5MOpA1NWQtuxEC1IB7VyR/qLs="
    - secure: "G0TruQHODQGLqKoSpFUlJ/zafz1Ywj559Wt9gMIrVcnDRIH/UoPtWfsg6Pvgz8SGGQn1DA1C1NojABmGmvG3W1ss1+s5KWXbhwd9VeLTyHNXiwsv4h9el/2ozip7FIVTtXTDainlabVFK6NDe1xlV7nPoGQlx76DaDmmm75oMFOzDuiFQauGGZ3hIuNisxwFa6jqgRWmKbP5mZcxEB+Kw1ZTfRcdb2FIfV4pNpJZ2D5wbe18JXADMigtrEHpr6L9gEcP9mSfbmVNC2ERC81BPX06nHRDUVn/aFbyig4MWXnPpCuziSuCc3MzV3j4o0XNhbbfFfIMbOghJ/3oucyXHhHaR9cT4q37RrBlNJaHWFThnTbV/zVDhF3j4e6XOBYKtHBBENm7UAiUHhR2Mxhs9NdY6+EDQO7HVDqrsod6d7b3l1UQGtPGCPUX2tpJKAZg4mSEkoJr0ti6NLPcqStAb3mXGedecE3GY1VXa+bm6e+f9srRfcZKQ7yxMaLK+1wsLDoljY0dsF90COQvNSHsxS3k7LHN80Q3QGaSRv0NWO8Tam3iSZ/HdqWRyUfj1NAnrvcwhAuwFiEFK6RJSvhziBk+jz/MEQwtGFPEM/yrjUGatZu/bmV/n1LWbKdCTfUIVHwlODkyEBJvW6a+0dC1UhXljYvQGBdsODojhUfyrcY="
    - secure: "E66YAXq7+lZC0HY0fkT5XuQKXKTcoKXjnfdKnKmjk3IUBFgWxJHQMhbWlm0QdCayKTuj37qrjnVQYMJxdUBeDPmHkmM2l3R30ZrPo8X11VeVf8k9vHiqBjEmRG8T+bLQKJe2GBquxO0v4zoOC/HoCynBIIJgvgbIywrfcGb/akvJC/ldInjpnpmDS2xFuzdv15hFehS4YI8cGsWCHI2TQfGcJc2Am6MtOBQnJI7AmVZx3D1AOlA5z/iYBgz/HNT9OYtc+kfNfhb4U7DhCES2VZNSBLk/nBE7OI3GvEn/7Gs7GwuDP4+1bBS/InheUnDI4DYRtHuYjZj0a7n0a6GoyftyT5A3hftIP+VPWmMQKPfkIfoSf1ZLz6fMgbe1BAlxDolY7LnDcD4Y0GXtH6eNalEAe1rwFSrAdKmooGgVIYIBA/F6DIt6uX/JuzyINJewVgBxygFm82TCflmqeeNd+oXKI6eoWT90AtKGaH4l9qhPE9chBtHpMEcTVtpq2Cgdw5pDsSuatrxb/rQK80tESs3D5menaryTnEXErXsqBov6dnALxrmiT5Yu+7SrHT9qyjajTQ2j71ndJq3rHO5D8r1MbCVlnoAyFwtUfTLLhUZekKSwKYKNaNsnTF9n2oIYP/uLvA+zKubueOJZoKmNbNDG8e/1V0SeLGIs1CypLi8="
services:
  - docker

before_install:
  - sudo apt-get update -qq
  - sudo docker pull ${DOCKER_IMAGE}

script:
  - sudo make bootstrap
  - make test-integration-clone
  - make docker-test

before_deploy:
  - travis_wait 30 make package

deploy:
  provider: packagecloud
  repository: main
  username: twindb
  token:
    secure: UjT3+/FY+Xw++BbqEgA7pCTN6PIIjtddDiGTu02BsjZwlq0JbF2Qee2RWUoVvKJII+cKIxcZkS1ovySSM8SSGGL1UG3Yu7tbDNU6ayhSAcjmHhKefj8eYDZKfOrDncW6IB2pjQZnMzt5oFYYee5/Hp4N7rP++mBD5oftJ0iYoY1v/OOdkrOde0+tl5vV4u1HyhtmScYIQiuwj/DGggIGAXt3os1pyAkQVtyVvb3HcBMV9tBG5rX7hax/FYWqgGEQUOZHwmQhALcmXrSohqYuSiFyBSxX9cDQ8f8VHKabITu+guMpXVNxwBE7n/YjL3JaKii7163uj7mc/pSmfRRuuPyZab1Of2IndFosFm49f8mwN1076PdJVGjijv+KkGOX1asZ4yh7/lt4TTdPqcDBaEROzp/skBlsEFY01ZBeiTHRNGG9rPXglpUnKQXikMaGCwOz/xqXcq81PwTWzgWAoPN74XIk0GfwYwQGsorCZGk8vcwFzdMCcS5xyGLMEDHBEPp24vxG/1UbWBtpiOwU5JIOKpUbkl5meIgZDaXqd4vyvL9wRv7vUvNn5DkCkAh5w7Mp2ACYU34iJb2SVvazKFmRvebXSXFoCSBkFBvTGAqzJoCxhlYhgDjOaRwUPZNaKMy86iCzOQjn3g5WpKBUEvf+eMk0ZVLf3P9mAOTOcqI=
  dist: ${DISTRO}/${OS_VERSION}
  skip_cleanup: true
  local-dir: omnibus/pkg/

notifications:
  slack:
    secure: "dKHhMOyQWZtaZZeaBgOvgk5natVRelxMcryvmjeqG/odTCfJXCD5geodYPsGLmkvA1qRdplGsGRmJnYEsUHeGTpUh3rlUd+j9iQ+pDcSD7d9EisL0lQji/DFek85NcMAXtiyNeKio5aukNXbGJT1cY4oHv/H2agk2TPC6hMKdDUk5hTpDKk4SAeHqpPYQzA5kthCCO+0y5Eh8zW5fiiH8FN+eID4FTt110bPDz3mNC4tzKExWw18dSB5m8ZxFQKQID8ZRedesBsGBdn4TMRObhjSwQOXIrV/Dif6BZjadA9MNoBvcQT6pCTmc4z0UVFR6MRVrIPwiIqaVI7jKp1ZUtVPVEa+Fui0TwRRSxPb78SCjKHc2jaVgsdxDE9Hk+0CXpZTUC4QG4+vBL0c4Ile2/qlhEXfIth6uOwzxyoNJ2zwxZarKpw3YvLKg23g7ZxfjAAGg4S8VUsNcaiSfGbSPAqQNa63KribP2Rp9/3IBNbuKwYvHyS8CxcAstTIKZkZg5BvRhDb1sv1UAyLum0qLI7e2Oz3SBAO+9ejoV5gnxl7iab89bg5XxuJiSjtcbwT3TNJ34ZdtWh/vnOjsz68DG71dK9VQ4rzg4/gpMY3YWARbKc/GTNUhBOeTtH0tmKWLEATP4VIHinu+QuBzs/9QlGqy1LhB2Ct4XkXPL3uMEk="
